language: node_js
branches:
  only:
    - master
before_install:
    - npm install -g gulp
    - git config --global user.email "ubiratan.f.soares@gmail.com"
    - git config --global user.name "Ubiratan Soares"
install:
    - npm install
script:
    - gulp build
    - gulp deploy
