language: node_js
branches:
  only:
    - master
before_install:
    - npm install -g gulp 
install:
    - npm install
script:
    - gulp build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./dist
  on:
    branch: master